### ISSUE TITLE
Type hint linting

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1002]
It should be possibly to lint the pyspec type hints. See [here](https://github.com/ethereum/eth2.0-specs/pull/996#issuecomment-487065832):

> You can run mypy/a linter on the output pyspec file

**Comment by hwwhww** [comment]
I've tried to add `mypy` tests - however, the current `SSZType` + `globals()` style type definition is quite incompatible with `mypy`...

I'd say we can solve it with `py-ssz`. :p

**Comment by djrtwo** [comment]
We can at least mypy and lint the beacon chain pyspec in CI

**Comment by hwwhww** [comment]
Appy `mypy` type hinting check with the current spec: 
```sh
mypy --follow-imports=silent --warn-unused-ignores --ignore-missing-imports --check-untyped-defs --disallow-incomplete-defs --disallow-any-generics -p eth2spec
```
Result:
https://gist.github.com/hwwhww/d000591903690fe9cc4a5eb8a09ee4a9

#### As I can see the problem is that the `def SSZType` + `class SSZObject` tricks are in runtime:
https://github.com/ethereum/eth2.0-specs/blob/f57d6fa28e151570e9c94807e6729a679fc7b1cf/test_libs/pyspec/eth2spec/utils/minimal_ssz.py#L10-L38

For example:
```python
Fork = SSZType({
    # Previous fork version
    'previous_version': 'bytes4',
    # Current fork version
    'current_version': 'bytes4',
    # Fork epoch number
    'epoch': 'uint64',
})
```

And the type checker cannot see functions defined at runtime.


#### On the other hand, `py-ssz` defines a container as a [ssz.sedes.Serializable subclass](https://github.com/ethereum/py-ssz/blob/4430c71d2c9f0a5613c9deb01f65cd3dda545d22/ssz/examples/zoo.py#L23-L29):
```python
class Animal(ssz.sedes.Serializable):
    fields = [
        ('id_hash', bytes32),
        ('public_key', bytes48),
        ('clock_in_records', List(ClockInRecords)),
        ('vaccinated', boolean),
    ]
```

So the fields are knowable to type checkers.

---

/cc @protolambda @dankrad

**Comment by JustinDrake** [comment]
@hwwhww: What is the status of this with the new SSZ typing?

**Comment by hwwhww** [comment]
@JustinDrake I was testing on the early version of the new SSZ, I will start to test on the dev branch now.
