### ISSUE TITLE
[Phase 1] `get_custody_chunk_count` is broken

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#1034]
### Issue
In [`get_crosslink_chunk_count`](https://github.com/ethereum/eth2.0-specs/blob/6242e54c0a0cf08f287830f0ddeab217cb2c9d25/specs/core/1_custody-game.md#get_crosslink_chunk_count) function, it uses `attestation.data.latest_crosslink.epoch` to calculate `crosslink_crosslink_length`, but `attestation.data.latest_crosslink.epoch` field is missing after #874.

**Comment by vbuterin** [comment]
The best solution I can come up with is to have the number of slots in the crosslink be explicitly listed in the attestation.

(Best to do it as a number of slots, because then we can most easily argue that it's the item length of an SSZ array of flattened block objects, so one could hash together the item length and root to get the SSZ root of the flattened block objects as a dynamic-sized list)
