### ISSUE TITLE
SSZ SOS: use endOffset instead of offset

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/eth2.0-specs#1087]
### The problem
The total SSZ message size can be determined only from external source like byte array size or size prefix and thus SSZ messages can't be simply streamed without envelope. 
From the other side we have excess information: offset of the first variable-size element - the `fixed_parts` size is statically known

### Proposal
For every variable-size element put its `endOffset` (instead of start `offset`), i.e. starting byte offset of the next variable-size element. The last `endOffset` in this case would be the total message size.

From my perspective this modification doesn't have any significant drawbacks comparing to the current scheme. Though may look slightly counterintuitive

@pipermerriam what do you think?

**Comment by Nashatyrev** [comment]
If that sounds good I would be happy to cook a PR

**Comment by pipermerriam** [comment]
I *thik* this works and is an improvement.

**Comment by Nashatyrev** [comment]
Cool! Then will make a poc on our Harmony Java client and get back with spec PR

**Comment by Nashatyrev** [comment]
> the fixed_parts size is statically known

Ups, that was wrong assumption. Doesn’t work for list with variable-size elements

**Comment by dankrad** [comment]
> Ups, that was wrong assumption. Doesn’t work for list with variable-size elements

I think you misread that:
```
We recursively define "variable-size" types to be lists and unions and all types that contain a variable-size type.
```
So a vector containing a variable-size element will also be variable-size itself and be in the variable_parts.

**Comment by pipermerriam** [comment]
I think what @Nashatyrev was trying to say is that this approach proved non-viable due to lists of variable size elements.  The reason is:

When you have a string of bytes that you know represents a list of variable size elements, the only thing you know is that the first 4 bytes are the first offset.  So, you read that.

In the current model where offsets denote the beginning of the variable size element, this first offset also defines the boundary between the two sections of SOS data.  By moving the offset to point to the end, the result is that you can no longer learn where that boundary is, and thus, it becomes impossible to decode such lists.

We **could** accommodate this via some special case, like including an extra offset for lists of dynamic size elements that denotes where this dividing point is, but I'm not very excited about that, and unless someone really wants to try and make a case for it being worth it....

**Comment by dankrad** [comment]
Ah, agree that we would need a special case for lists. What would make sense is if we treat the offset list itself as one of the variable-size elements in this case, and add an end offset.

**Comment by protolambda** [comment]
To do zero extra allocations when decoding a list of variable-size elements, I:
1. read the first offset
2. use that to compute the count of items, or amount of offsets really (`length = offset / bytes_per_offset`)
3. I can then initialize a slice that will hold the values (I know the memory size of the type of the elements I'm decoding into, e.g. a slice as element is just a slice-header, and I can allocate the exact memory for it).
4. After that, check the offsets I just read in between decoding the variable-size elements one by one
5. Until I handled the last offset.


Changing to end-offsets would break that nice efficiency, and I'd have to grow (i.e. unnecessary allocations!) the list as I read end-offsets until I hit an offset that matches the end of the scope.

A simple quality of life change would be to just start with the length of the list, as 4 bytes, and then do end-offsets. Then you can allocate the list of items ahead of time, and using this length, you can identify the last end-offset when you get there in your stream, without relying on the context (envelope) telling you where the end is.

That is just 4 bytes per list, and gets you clean list initialization + careless streaming of any SSZ object (no envelope). I think that's worth it. But I'm fine with status quo.
