### ISSUE TITLE
Understanding the `get_new_shuffling()` function

### ISSUE THREAD

**Issue by Mikerah** [ethereum/eth2.0-specs#127]
For the past several weeks, as part of my hackternship, I have been trying to understand the `get_new_shuffling()` function. In its current iteration, the `get_new_shuffling()` function is in charge of sorting validators into committees and associating a committee to a particular shard for a particular cycle and a slot in that cycle. The shard in question is one that has a crosslink from the committee that was given by `get_new_shuffling()`. 

Is the above right?

My main question is what is the motivation for selecting committees in this way?

**Comment by Mikerah** [comment]
Also, `crosslinking_start_shard` is used to create `shard_id`'s but where do is come from and who provides it?

**Comment by djrtwo** [comment]
When there is a validator set change due to all required crosslinks being created and finality occurring, we use `crosslinking_start_shard` is simply the last shard from the last committee in the last shuffling plus 1. In the case where there are enough validators/committees to crosslink all shards each shuffling, this will always jsut start at the same shard.

When there is not a validator set change, but just a reshuffling, we use the same crosslink start shard as previous so that we get new committees for the same shards.

The shard in question is not just the shard_id passed in. That is just the _start_ shard. It is one shard per committee. If 100 committees are produced from the shuffling and the start shard passed in was 150, then it produces committees for shards 150 to 249. 

Check out the line
```python
shard_id_start = crosslinking_start_shard + slot * committees_per_slot
```

**Comment by Mikerah** [comment]
Aah. That makes more sense. Thank you so much.
