### ISSUE TITLE
Ineffective "Fiat-Shamir" protection with active_index_roots mix-in

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1273]
Light clients that use `compact_committees_roots` as their authentication root for the active validator pool do not benefit from the mixing of `active_index_roots` in `get_seed`. Indeed, an attacker can fiddle with `compact_committees_roots` while keeping `active_index_roots`   fixed (and hence keeping the shuffling fixed).

**Comment by vbuterin** [comment]
It turns out that "Fiat-Shamir protection" is not necessary if we just commit to the crosslink (and in phase 1 persistent) committee directly. A block at time T would commit to the crosslink committee at time T + 4 epochs, and to the persistent committee at time T + 9 days, so you can just hop forward through the "use a Merkle path from a block to determine the public keys for a future block, verify the signature of the future block, repeat" technique. This is good news because it really reduces the complexity of a light client; we're talking about ~200 kb per ~9 days in the worst case, and there's ways to improve on those numbers.

**Comment by JustinDrake** [comment]
The suggestion is to remove `active_index_roots` from `BeaconState` and `get_seed`. In the worst case that saves ~67MB of data hashing per epoch.

**Comment by dankrad** [comment]
> The suggestion is to remove active_index_roots from BeaconState and get_seed. In the worst case that saves ~67MB of data hashing per epoch.

I am still a fan of this as I also think it make RANDAO cleaner and removes it from considerations what exactly we can do with the validator set.

**Comment by JustinDrake** [comment]
> I also think it make RANDAO cleaner

Why?

> A block at time T would commit to the crosslink committee at time T + 4 epochs

This doesn't work if there are no blocks in some epoch.

**Comment by dankrad** [comment]
> > I also think it make RANDAO cleaner
> 
> Why?

Separation of concerns. It is unsafe to mix data into RANDAO, as that data may be influencable. In particular, it was only safe to mix in active_index_roots because it can only change on slower timescales than RANDAO. If someone in some protocol version/iteration/fork decides that some action concerning validators should take immediate effect, it could compromise RANDAO.

**Comment by JustinDrake** [comment]
Fixed with #1329 🎉
