### ISSUE TITLE
Blocks added to the store before some verifications

### ISSUE THREAD

**Issue by terencechain** [ethereum/eth2.0-specs#1288]
The  block gets added to the store before checking it's a descendant of the finalized block and later than the finalized epoch slot. Any reason it is added before those verifications? 
The appropriate spot looks to be after state transition 

<img width="633" alt="Screen Shot 2019-07-10 at 6 53 21 PM" src="https://user-images.githubusercontent.com/21316537/61016398-545d1200-a344-11e9-9db9-b248f9221593.png">

**Comment by hwwhww** [comment]
Because with the current algorithm, the given block would be queried in `get_ancestor(store: Store, root: Hash, slot: Slot)` function recursively.
I had the same question before: https://github.com/ethereum/eth2.0-specs/pull/1068#discussion_r285386568, but we haven't figured out a better solution yet.

We do want to make the fork choice rule spec more abstract in the spec level, however for sanity testing, the `Store` is exposed as status quo. IMO it might need more iterations past spec freeze to make it better.

**Comment by JustinDrake** [comment]
@terencechain: Can we close this?

**Comment by terencechain** [comment]
Sure and to clarify this is just a presentation issue. In Prysm, we add the block to fork choice store after `state_transition`
