### ISSUE TITLE
Run linter with `make test`

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1330]
I've been caught a few times by `make test` not linting my PRs and CI throwing lint errors. Also `make lint` is not documented. I suggest running the linter with `make test`.

**Comment by hwwhww** [comment]
From my experience, the convenience of the separation are:
1. We can make sure the lightweight `make lint` checks pass first, then try to make the heavyweight `make test` pass when developing.
2. In CI result, it's clear to know the issue happens due to the correctness or just formatting.

An alternative solution to address it is adding a `make test_and_lint` command.

**Comment by djrtwo** [comment]
I'm pro the separation. 
The output of combining the two in a local make command might be a bit opaque

**Comment by JustinDrake** [comment]
Ok, let's keep `make test` and `make lint` separate :)
