### ISSUE TITLE
Signature of validator `deposit` inconsistent

### ISSUE THREAD

**Issue by mcdee** [ethereum/eth2.0-specs#1422]
The current signature of the validator's `deposit` function has both `bytes[32]` and `bytes32` parameters:

```
def deposit(pubkey: bytes[PUBKEY_LENGTH],
            withdrawal_credentials: bytes[WITHDRAWAL_CREDENTIALS_LENGTH],
            signature: bytes[SIGNATURE_LENGTH],
            deposit_data_root: bytes32):
```

Would it not make sense to have the final parameter be `bytes[32]` so that it is consistent?

**Comment by protolambda** [comment]
I assume you are talking about `WITHDRAWAL_CREDENTIALS_LENGTH`? Since the signature and pubkey are 96 and 48 bytes respectively, only declarable with `bytes[...]`

- `bytes32` is a special vyper type, see https://vyper.readthedocs.io/en/v0.1.0-beta.13/types.html#bit-wide-byte-array
- `bytes[WITHDRAWAL_CREDENTIALS_LENGTH]` may not be consistent with a `bytes32`, but seems more consistent with the other parameters. Also, it is more readable in my opinion.

RE changing the `bytes32`: I think it's worth it to keep the final parameter `bytes32`, as it's a widely used type, always 32 bytes, and clean to convert to a uint256 or `bytes[X]` where needed.

@hwwhww Do you have an opinion here?

**Comment by mcdee** [comment]
The spec defines `withdrawal_credentials` as a hash, which is also the output of `hash_tree_root()` so you have two hashes with different data types in the same function.  Just seems weird.

**Comment by protolambda** [comment]
Yes, I am not a fan of the `Hash` as it's also just confusing with `hash()` (the function). Changing it to bytes32 would work, but it may be better to change all `Hash`. For a different issue though, and that pressing as some other things.

**Comment by hwwhww** [comment]
The parameterized `WITHDRAWAL_CREDENTIALS_LENGTH` was for making it clearer in the length checks. But @daejunpark is considering removing the length checks later (see the discussion from this thread: https://github.com/ethereum/eth2.0-specs/pull/1362/files#r320008295).

I personally think `bytes32` is a common alias in Vyper contracts. After the length checks are removed, we could either keep parameters:
```python
def deposit(pubkey: bytes[PUBKEY_LENGTH],
            withdrawal_credentials: bytes[HASH_LENGTH],
            signature: bytes[SIGNATURE_LENGTH],
            deposit_data_root: bytes[HASH_LENGTH]):
```
or just
```python
def deposit(pubkey: bytes[48],
            withdrawal_credentials: bytes32,
            signature: bytes[96],
            deposit_data_root: bytes32):
```

**Comment by mcdee** [comment]
@hwwhww I'd have a slight preference for the former of those options, but either would be an improvement.

**Comment by djrtwo** [comment]
Although there is arguably a minor inconsistency in choosing types here, we're going to leave as is to keep stable wrt formal verification
