### ISSUE TITLE
a suggestion allowing suspension of validator waive of penalty.

### ISSUE THREAD

**Issue by chenlocus** [ethereum/eth2.0-specs#1425]
Hi there, I saw this "Users need to make sure their validator doesn't have downtime or they risk a quadratic leak on their stake.“  Is there a way for validator to suspend service due to maintenance ? Otherwise it is quite unfair to validator who want to switch server or do maintenance job. So during the suspension period, they won't get reward.

The original proposal would scare off lots of ordinary people who want to join validators team, which requires redundant validator client.  People using their own computer to validate may encounter power off, computer upgrade. This will happen even if people use aws.

**Comment by dankrad** [comment]
Users will only face a quadratic leak if the chain is not finalizing, i.e. at least 1/3 of validators are offline overall. Otherwise it is a small penalty, similar order to rewards.

It will only have a very small impact if it only happens for a few hours or a day. I generally agree that this could deter a few people from becoming validators, and I think the impact of allowing say 1 day of downtime per year would be very small. However, it's probably not worth the added complexity.

**Comment by djrtwo** [comment]
In normal chain finality conditions, having ~50-60% uptime keeps a validator in the black. Being about to suspend validation introduces significant consensus complexity and the validator would still be subject to activation/exit queues/times. 

Once validator Transfers are added, the normal flow for suspending would be to exit, then to later Transfer eth to a new validator account for new activation.
