### ISSUE TITLE
New shard proposal issues

### ISSUE THREAD

**Issue by vbuterin** [ethereum/eth2.0-specs#1429]
See https://github.com/ethereum/eth2.0-specs/pull/1427

1. Do we separate attestation shard updates (list of intermediate state roots and block data)? Reason to do this is to avoid including unneeded data for losing attestations, increasing data efficiency.
2. Block data in 128 kB chunks (for easier and more compact data availability root construction) and shard state increased from 32 bytes to 128 bytes (to allow recovery from up to 3 bad crosslinks, and to allow Merkle branch constructions to tolerate transactions created a few blocks previously)
3. Slowing down shard block production if there are no crosslinks: https://github.com/ethereum/eth2.0-specs/issues/1449
4. Shard blocks should point directly to parents, instead of having "empty slot filler blocks"?
5. Attestations and custody bits proposal: https://github.com/ethereum/eth2.0-specs/issues/1448

**Comment by mcdee** [comment]
Regarding 4), can we realistically expect the network to propagate the attestations of all well-behaved validators within a single slot?  If not, could mechanism be a little more forgiving, for example `1/(1+inclusion_delay//4)` (for expecting full propagation within 3 slots; change 4 as appropriate)?

**Comment by vbuterin** [comment]
> 4), can we realistically expect the network to propagate the attestations of all well-behaved validators within a single slot?

I hope so! If it can't, then we should increase slot duration until it can.

**Comment by djrtwo** [comment]
1. pro separation
2. “shard state increased from 32 bytes to 128 bytes” — not sure what you mean by the size of shard state here
3. I’m in favor of the slowed down chains. at least favor this over reduction of block size/gas limit
4. As discussed, having empty blocks for empty slots leads to a lot of weird scenarios and hard-to-find blocks for empty hashes. We’ve gone down this road a couple of times in the past. I don’t immediately remember all of the pitfalls but when we began to discuss in person, it seemed that we might hit them here again. I think creating a chain of just actual user-created blocks is simpler than the empty proposal, but am open to exploring it if there are any clear potential advantages
5. Proposal makes sense. It does raise the max size of some objects other than just the attestations — AttesterSlashing of note. puts it in the ~150MB range instead of ~50MB. Seems fine but need to keep it in mind

**Comment by hwwhww** [comment]
Replaced by #1768
