### ISSUE TITLE
Slowing down shard activity if crosslinking fails

### ISSUE THREAD

**Issue by vbuterin** [ethereum/eth2.0-specs#1449]
In the case where blocks from a shard are not crosslinked for a long time, there is a chain of shard blocks of growing length that must eventually be included in a shard block. Currently, the intention is that these blocks can be included a maximum of 256 at a time.

However, there are challenges to this approach:

* In an attestation, we have to choose between either (i) creating an attestation with many custody bits, adding complexity and overhead to handle this or (ii) using one custody bit over many blocks, requiring a 2-round game for fraud proofs.
* In an attestation, a large amount of data representing shard blocks and intermediate state roots would need to be included
* There are two cases in which crosslinking can be delayed:
  1. There are very few validators online so only a few shards are processed every slot, requiring many slots to cycle back to any given shard (eg. at 256k ETH, it takes the maximum 64 slots)
  2. There is an active attack due to committees being >1/3 inactive
* In the first case, there are very few validators, so it is not reasonable to ask them to verify so much data, so a reduction in the shard chain capacity seems correct. In the second case, reduction in capacity during an attack also seems like a reasonable safety measure, especially in the case where an attack happens due to network DoS.
* There is limited value in preserving high performance for intra-shard communication when cross-shard communication is stalled.

To remedy these issues, I suggest adding the following rule. Suppose the current slot is `CURRENT_SLOT` and the shard chain on a given shard was included up to `LAST_INCLUDED_SLOT`. We define a set of offsets, eg. `offsets = [1, 2, 4, 8, 16, 32, 64, 128, 256]`, and require an attestation to include blocks for slot `LAST_INCLUDED_SLOT + offset` for any offset in `offsets` such that `LAST_INCLUDED_SLOT + offset < CURRENT_SLOT`. That is, if crosslinks stop happening, the slots on a shard chain that are allowed to be nonempty start to back-off exponentially.

Offsets can be chosen to be more "forgiving" at the beginning, eg. one could choose Fibonacci numbers instead of 2: `[1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233]` or even `[1, 2, 3, 4, 5, 6, 7, 8, 12, 16, 32, 64, 128]`.

### Why not shrink shard blocks instead of increasing inter-shard-block distances?

* Simpler: does not require logic for fitting multiple shard blocks into a single custody bit or fraud proof object
* Removing capability of including large transactions may well be _more_ harmful than increasing block times, eg. consider large fraud proofs, STARKs, etc
* We lose fast cross-shard tx times in these circumstances anyway

**Comment by dankrad** [comment]
I think this is a good idea! I think I've suggested the reduction mechanism before, with my main reason being that otherwise, the load on validators will increase by an unreasonable amount when crosslinking stops. This might create negative feedback loops that lead to more validators dropping out in bad network conditions, and might also be exploitable by an attacker.

>     * In an attestation, we have to choose between either (i) creating an attestation with many custody bits, adding complexity and overhead to handle this or (ii) using one custody bit over many blocks, requiring a 2-round game for fraud proofs.

I actually quite like suggestion (i), I think it will be a lot less complex than dynamically introducing a two-round custody game.

Also, I think realistically, the two-round custody proof will not be executable by MPC validators in the given time now (except if they are in colocation). But since these custody bits can be computed independently, the load will actually not increase with solution (i). So that's a big advantage -- I think it

> Why not shrink shard blocks instead of increasing inter-shard-block distances?

I think the idea to skip block instead of shrinking them is great! Processing a block will presumably also have its own overhead so this is a much more efficient way of shedding load.

**Comment by vbuterin** [comment]
> I actually quite like suggestion (i), I think it will be a lot less complex than dynamically introducing a two-round custody game.

I agree! And it's not that complex at all, here is a design that ensures that the increase in pairings for N custody bits is linear rather than exponential: https://github.com/ethereum/eth2.0-specs/issues/1448

Glad that we're still on the same page re sticking to one-round custody games; I think the ability to have "one fraud proof to rule them all" is a huge simplification that we should try hard to stick to.

**Comment by hwwhww** [comment]
> There are two cases in which crosslinking can be delayed:

Is there also a case: if the beacon chain block slot is skipped?
