### ISSUE TITLE
【Please click in and help me!!!!】How to run eth2.0???

### ISSUE THREAD

**Issue by yeeacksonideo** [ethereum/eth2.0-specs#1503]
I am a student,It's about my graduation project。I want to know how to run eth2.0,and especially，I want to know how to test the part of random number generation----- randao!!!!1

**Comment by mratsim** [comment]
You have a couple of testnets available for running here: https://github.com/eth2-clients/eth2-testnets feel free to pick one.

Regarding the RANDAO it is specified here: https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#randao

```python
def process_randao(state: BeaconState, body: BeaconBlockBody) -> None:
    epoch = get_current_epoch(state)
    # Verify RANDAO reveal
    proposer = state.validators[get_beacon_proposer_index(state)]
    assert bls_verify(proposer.pubkey, hash_tree_root(epoch), body.randao_reveal, get_domain(state, DOMAIN_RANDAO))
    # Mix in RANDAO reveal
    mix = xor(get_randao_mix(state, epoch), hash(body.randao_reveal))
    state.randao_mixes[epoch % EPOCHS_PER_HISTORICAL_VECTOR] = mix
```

with randao mix being just an array storing crypto mixes
```python
def get_randao_mix(state: BeaconState, epoch: Epoch) -> Bytes32:
    """
    Return the randao mix at a recent ``epoch``.
    """
    return state.randao_mixes[epoch % EPOCHS_PER_HISTORICAL_VECTOR]
```

Hash being sha256, and randao_reveal being derived from user private data and the source of entropy.

The spec is executable so you can run it and dissect how every elements work, please see instructions here: https://github.com/ethereum/eth2.0-specs/tree/dev/test_libs/pyspec

PS: As a general advice, I understand that you might be either excited or pressed for time or not be a native English speaker but your title and your text could be seen as rude and/or spammy due to the special characters to draw attention and the massive amount of exclamation marks.
