### ISSUE TITLE
Inconsistent merkle root algorithm in deposit contract

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/eth2.0-specs#1565]
Was reviewing the deposit contract to see if anything popped out at me and noticed the following lines which seemed strange:

https://github.com/ethereum/eth2.0-specs/blob/2e3fcc16f19463bf2e6a95f30489ba51b6aba174/deposit_contract/contracts/validator_registration.vy#L52-L54

I believe it makes sense in context, but considering it departs from most normal formulations of the algorithm, it should probably have a link to documentation that supports the modified structure for others to reference.

**Comment by djrtwo** [comment]
This is a specific construction used to save gas. Because it is a binary merkle tree filled with 0s to start and leaves only added sequentially, we can use an incremental algorithm that greatly saves gas.

There is a formalization/discussion of the algorithm here

https://github.com/runtimeverification/verified-smart-contracts/blob/master/deposit/formal-incremental-merkle-tree-algorithm.pdf

Once the entirety of the formal work done on the contract is published in the next couple of weeks, we will add links to it all in the repo

**Comment by fubuloubu** [comment]
Thanks, I loosely knew what the reasoning was, but at first glance it seems like a mistake. I'll leave this issue open as a reminder to add a comment linking to the documentation.

**Comment by djrtwo** [comment]
This is noted in the deposit contract readme -- https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/deposit-contract.md#vyper-code
