### ISSUE TITLE
Can "Inactivity Leaks" handle 1/3 validators offline in the same time?

### ISSUE THREAD

**Issue by kevinho** [ethereum/eth2.0-specs#1572]

**Comment by djrtwo** [comment]
I'm not 100% sure what you mean here.

Inactivity leaks continue to occur in state transitions even if justification/finality is not occurring. So yes, inactivity leaks can happen when 1/3 are offline. 

This is because the chain building mechanism can remain live even if the finality mechanism is not. This is important because if a portion of the validators are permanently (or a long time) offline, the inactivity leak can ensure that the online portion can eventually become a 2/3 majority and finalize

**Comment by kevinho** [comment]
@djrtwo thanks for reply.
As far as i can image, when 1/3 validators are offline, there would be no new block generated, how can the inactivity leak continue to work? 
What do you mean by "chain building mechanism"? Any docs about this?

**Comment by dankrad** [comment]
> As far as i can image, when 1/3 validators are offline, there would be no new block generated, how can the inactivity leak continue to work?

Blocks can still be generated, but they won't be finalized.

**Comment by kevinho** [comment]
@dankrad any documentation of specs about this?

> > As far as i can image, when 1/3 validators are offline, there would be no new block generated, how can the inactivity leak continue to work?
> 
> Blocks can still be generated, but they won't be finalized.

**Comment by dankrad** [comment]
@kevinho just like if you want to trust the latest block in the Bitcoin chain, you can, but there is a small chance that a different chain will turn out to be the longest. If you want more safety, you wait for a number of confirmations (e.g. 6).

The Ethereum 2.0 fork choice uses LMD GHOST for non-finalized blocks. Think of if as putting the Casper FFG gadget (https://arxiv.org/abs/1710.09437) on top of an LMD GHOST generated PoS chain.

**Comment by djrtwo** [comment]
👍
