### ISSUE TITLE
Remove recursive use of BeaconBlockHeader.StateRoot inside state

### ISSUE THREAD

**Issue by sgryphon** [ethereum/eth2.0-specs#1643]
The definition of BeaconState includes latest_block_header, which includes a field for state_root; a recursive reference back to the hash of the state.

This is already recognised, and because of this, for states where a block is received, the stored value always includes a zeroed state_root; the actual state root is then calculated during slot processing in order to validate the next block's parent.

However, the calculate value is temporarily inserted back into the state, even though it will be zeroed again by block processing.

i.e. inserting the calculated value into the state has no purpose, as it is overwritten anyway (you still need it for validation; just no need to insert).

Note also that the stored BeaconBlockHeader is useless as is, it can't be compared directly to a block, as it needs to have state_root inserted first.

One consequence of temporarily changing the header state_root inside state is that state then becomes inconsistent, i.e. if you recalculate state_root for some reason you get a different value. (Obviously if you recalculate in the middle of processing it will be different, but this change is only temporary)

I suggest something like:

* Change the definition of BeaconState to include fields directly for latest_block_slot, latest_block_parent_root, latest_block_body_root, instead of BeaconBlockHeader

* During processing calculate state_root as currently done, then combine with the fields from state to create a BeaconBlockHeader, and hash that to re-generate the block root when needed.

Note that there are implications for empty slots, as you would need to calculate the first state root (corresponding to the block), not the state_root of the empty slots.

**Comment by djrtwo** [comment]
> However, the calculate value is temporarily inserted back into the state, even though it will be zeroed again by block processing.

It will only be zeroed out _if_ there is a block at that slot. The `latest_block_header` is important for verifying parents of arbitrary skip slots, especially in the context where sub-components of the state transition function are used locally (e.g. empty slots processed when no block comes in to figure out shufflings in future epochs).

> One consequence of temporarily changing the header state_root inside state is that state then becomes inconsistent

This is true of all intermediate states during the state transition function. It is only safe to get the state root before and after a state transition. Otherwise, the intermediate root will certainly not be valid.

> During processing calculate state_root as currently done, then combine with the fields from state to create a BeaconBlockHeade

There are two issues that emerge here -- (1), the `pre_state_root` would then need to be passed around to various functions in the state transition for validation and (2), this makes transitioning the state forward during skip slots (without a new head block) more cumbersome as the client would need to calculate and pass in the post-state root of the latest slot with a block.

I don't see a fundamental issue with the approach as is. It keeps structures clean and allows for a simple use of the state transition and sub-functions. It also works well and is widely integrated into clients at this point. This has been widely debated over the past year and I think all involved are happy with the equilibrium. Even for the sake of keeping things stable in light of coming mainnet, I say leave as is.

**Comment by JustinDrake** [comment]
@sgryphon Are you satisfied by @djrtwo's response? :)
