### ISSUE TITLE
v0.11.0 Gossip verification questions

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#1659]
I'm seeking come clarity around two points in the [Global topics](https://github.com/ethereum/eth2.0-specs/blob/v0.11.0/specs/phase0/p2p-interface.md#global-topics) section of `v0.11.0` of the p2p-interface spec states, please :)

## A. First block for the proposer of the slot

> The block is the first block with valid signature received for the proposer for the slot, signed_beacon_block.message.slot.

Could you please confirm if the following accurately reflects the intention of the above statement?

_The block is the first block with a valid signature received with the given slot and proposer index tuple: `(signed_block.message.slot, signed_block.message.proposer_index)`_

If this is the case, then a simple hash-set of `(slot, proposer_index)` which is updated after signature verification should be sufficient to check this condition.

## B. Proposer signature verification

> The proposer signature, signed_beacon_block.signature, is valid.

There are (as of v0.11.0) two things for checking a block signature validity:

1. Was the signature produced by the validators public key?
1. Was the validator scheduled to propose the block at the slot?

I'm looking for some clarity about if we should include (2) in the verification.

**Comment by mkalinin** [comment]
> I'm looking for some clarity about if we should include (2) in the verification.

If we do not we have a DoS vector. Adversary owning `N` validators is able to flood network with at least `N-1` blocks in each slot.

**Comment by paulhauner** [comment]
> If we do not we have a DoS vector. Adversary owning N validators is able to flood network with at least N-1 blocks in each slot.

I agree, verifying 2 seems to be pragmatic.

**Comment by djrtwo** [comment]
I think we add a condition "The block is proposed by the expected proposer_index for the slot in the context of the shuffling (defined by parent/slot)"

and maybe also "If the proposer_index cannot immediately be verified against the expected cache, the block MAY be queued for later processing while proposer caches are recalculated"

This reduces the DoS vector of out of unexpected blocks (e.g. built on some long past parent) to be one that can be handled on a per-case basis in the client rather than prescribing a MUST or MUST NOT process. In normal operation if you got one weird block, you oculd go check it out, but if you get `N`, you can drop.

**Comment by mkalinin** [comment]
I totally agree. We should not obligate clients to verify all those blocks, but a block that hasn't been verified must not be propagated.

Btw, once we change leader election algorithm we could slash for ineligible proposals. It would significantly reduce the DoS vector.

**Comment by djrtwo** [comment]
And yes @paulhauner, confirmed on [A]

**Comment by djrtwo** [comment]
Addressed in  #1661
Appreciate some review

**Comment by paulhauner** [comment]
Thank you! Sorry I came back to this late and didn't review.

Feel free to close at will :)
