### ISSUE TITLE
DepositContract: to_little_endian_64 and its inputs

### ISSUE THREAD

**Issue by axic** [ethereum/eth2.0-specs#1726]
`to_little_endian_64` [states here](https://github.com/ethereum/eth2.0-specs/blob/dev/deposit_contract/contracts/validator_registration.vy#L34) that it's inputs always fit 64-bits. To me it seems this is technically not true, albeit very unlikely to every be exploited.

This helper is used for two values: `deposit_count` and `deposit_amount`. There is an assertion for `deposit_count < 2^32-1`, however none for `deposit_amount`.

The only way to overflow `deposit_amount` is by sending a transaction with value larger than `2^64-1 * 10^9` (in wei), which is unrealistic, but given the contract already has a couple of assertions, probably the cost of an additional one wouldn't be a problem.

Is this just a) missed; b) intentionally like this; c) or I have messed up something?

**Comment by djrtwo** [comment]
Since the amount passed to the `to_little_endian_64` function is in Gwei,  2^64 means ~18 billion (~ 10^10) Ether, which is greater than the current supply ~110 million Ether.   

We discussed this during audit/formal verification and let it pass due to the infeasibility in mainnet conditions.

There used to be a `assert deposit_amount <= MAX_DEPOSIT_AMOUNT` but this was removed in favor of allowing deposits higher than `MAX_DEPOSIT_AMOUNT` (32 ETH) as an acceptable input (the user can just top-up balance even if this bound was in place).

Fortunately, even in the case that the depositor does deposit `>= 2^64` ETH, `to_little_endian_64(deposit_amount)` will return (the little endian representation of)  `deposit_amount mod 2^64`.  So, the depositor will lose funds rather than minting funds.

I'm not opposed to adding an `assert deposit_amount < 2^64` but also don't necessarily want to disturb the FV unless we open it up for other reasons.

**Comment by axic** [comment]
> Fortunately, even in the case that the depositor does deposit >= 2^64 ETH, to_little_endian_64(deposit_amount) will return (the little endian representation of) deposit_amount mod 2^64. So, the depositor will lose funds rather than minting funds.

Good point, perhaps it is enough to mention this in the source code (a single line comment) and the specification.

**Comment by djrtwo** [comment]
single line comment makes sense. I'm happy to add this in with next release

**Comment by djrtwo** [comment]
solidity contract is frozen!
