### ISSUE TITLE
Double (invalid) slashing tests

### ISSUE THREAD

**Issue by protolambda** [ethereum/eth2.0-specs#1760]
Tracking isssue, we should test double slashings. Lighthouse had a bug here, caused by over-optimization that was unaccounted for in the spec: https://github.com/sigp/lighthouse/issues/1065

The tests should cover:
- Two proposer slashings in the same block, for the same proposer, making the block invalid
- Two attester slashings with overlap in attesters in the same block, similar to above. 
  - Valid case: different sets of attesters with overlap, repeated in two attester slashings, but overlap should not be slashed twice.
  - Valid case: one attester twice, no other participants

**Comment by djrtwo** [comment]
I'd like to leave this issue open even after the close of #1781

I think it worth considering upping `MAX_ATTESTER_SLASHINGS` to 2 in `v0.12`. The main reason to keep it low is due to [size considerations](https://docs.google.com/spreadsheets/d/19ZGbIFaIi5quIvpB3Aa3VRgurKPBG9NMrJB7LGMBwXI/edit#gid=0) (max ~33kb per `AttesterSlashing` when 4M validators), but in lower ranges of validators (say ~300k validators) this is more like ~3kb.

The other added benefit is that it takes half the amount of time to fully slash an attacker when a serious attack is found

cc: @vbuterin for thoughts on upping the value of this constant

**Comment by protolambda** [comment]
@djrtwo Can we close this issue now, with the tests in #1794 ?

**Comment by djrtwo** [comment]
yep!
