### ISSUE TITLE
Gossipsub v1.1 peerscoring of "Invalid Messages" might be problematic

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#1761]
There has been an incredible effort put into [gossipsub v1.1](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md) in the past few months to harden the protocol against a wide range of attacks.

One of the key mechanisms is the utilization of [peer scoring](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#the-score-function) in the gossip layer. When reviewing the protocol, I realized that "P₄: Invalid Messages" might be problematic wrt how we utilize application layer validations in a few cases.

Copied directly from the [gossipsub v1.1 peer scoring spec](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#the-score-function):
> P₄: Invalid Messages for a topic. This is he number of invalid messages delivered in the topic. This is intended to penalize peers who transmit invalid messages, according to application specific validation rules. It is mixed with a negative weight.

My concern is that some of our conditions are used to flag messages as "not worth forwarding" rather than as specifically marking as "invalid" or "malicious". And in the case where the message might be seen as malicious from a global perspective (double attestation per epoch), the sending peer does not necessarily know the message will be invalid before sending it (e.g. sending peer doesn't know receiving peer already received an attestation from val-A this epoch and sends a different (locally valid looking) attestation from val-A).

One such condition is found in `beacon_aggregate_and_proof`:
> The valid aggregate attestation defined by `hash_tree_root(aggregate)` has _not_ already been seen (via aggregate gossip, within a verified block, or through the creation of an equivalent aggregate locally).

In the (optimal) case that many aggregators agree on the same aggregate attestation, this condition prevents all of the duplicates from being fully gossiped on the network, and does not signal that an invalid or malicious message was sent (and thus a cause for de-scoring).

Dealing with this (while retaining the usefulness of "P₄: Invalid Messages" in the scoring function)  will either need to change our spec or the gossipsub spec.

Immediately obvious options:
* remove such conditions from our spec. I'm not certain we can remove all of them because many are DoS mitigations (no duplicate attestation from single validator per epoch) rather than simply optimizations.
* change the gossipsub spec such that the callback returns a `True/False/DO_NOT_FORWARD` where `True` is valid+forward, `False` is invalid+drop, `DO_NOT_FORWARD` is not fully invalid but still drop. This isn't an immediately palatable path without having some more in depth discussions about the possibilities and more general gossipsub usecases.

^ neither of the above is fully thought through a solution. Putting this out for discussion and thinking about it some more.

**Comment by djrtwo** [comment]
CC: @AgeManning @nisdas @arnetheduck @raulk

**Comment by terencechain** [comment]
I echo this concern. Here's some stats captured in Topaz testnet:
 * ~35% of the `beacon_block` are filtered out due to duplication
 * ~50% of the `beacon_aggregate_and_proof` are filtered out due to duplication

The callback makes sense to me for the long term and it's also not a testnet breaking feature

**Comment by djrtwo** [comment]
> ~35% of the beacon_block are filtered out due to duplication

What is the de-duplication method here? Is it just the native gossipsub `message-id`/cache mechanism, or is this an application specific gossip condition? For beacon blocks, I wouldn't expect an application specific condition doing this unless people were double proposing. If it's just the native gossipsub `message-id` de-duplicating, that's okay and won't cause peer de-scoring

> ~50% of the beacon_aggregate_and_proof are filtered out due to duplication

That's awesome to hear! working as expected :)
Some of this might be de-duplication from `message-id` but I'd expect a high number to be duplicates from different aggregators (which wouldn't be caught by `message-id` because the wrapping `AggregateAndProof` would be a different message even if the contained `Aggregate` is the same

**Comment by terencechain** [comment]
> What is the de-duplication method here?

The condition is `first block received for the proposer for the slot...`  This well could be a bug in our end. Tracking via: https://github.com/prysmaticlabs/prysm/issues/5630

**Comment by raulk** [comment]
Hey team! Thanks for detecting and reporting this. We’re looking into solutions and will get back to you today. But on surface, enhancing the signature of the validator to return an enum instead of a boolean such that we can signal “deliver/forward-only/drop” conditions seems like the way forward here.

In the reference implementation (Go), we can add a new interface to preserve backwards compatibility, and shim the old one into the new one.

Will get back to you definitely after we finish this discussion within the libp2p team today.

**Comment by vyzo** [comment]
We have been considering extending the validator interface for some time, so that it can provide richer feedback to the pubsub subsystem and address concerns similar to the ones identified in this thread.

Following internal discussion, we have decided to extend the validator interface to provide an enumerated (instead of binary) response with a minimum of three possible values: Accept, Reject, or Ignore.
- Accepting or Rejecting a message is the familiar accept/reject decision from the original validator interface, whereby a Reject will trigger the P4 penalty.
- The Ignore response is the desired new behaviour which drops the message (and does not deliver it to the application or forwards it to the network), but without triggering the P4 penalty in scoring.

To this extent, we have updated the gossipsub v1.1 spec to document this new behaviour.

The PR for the extension is here: https://github.com/libp2p/specs/pull/265, and we would appreciate your feedback as implementers, if possible by the end of the day today (whenever that is for you :)).

We are working on incorporating these changes into the go-libp2p-pubsub reference implementation, and we should have an implementation PR soon.

There’s one open question. AFAIU, the three values in the enum are sufficient to model the current behaviour. However, they’d be insufficient to signal a case where you want the message to be forwarded to peers (via mesh and gossip), without being delivered to the application, or vice versa. Do you foresee such situations? We can easily extend the enumerated response to support this use case.

PS: We have also identified another situation where the ternary response applies: the application may be unable to ascertain the validity of new messages because it is first syncing or resyncing its chain. We had encountered this problem in Filecoin, and this had first prompted us to explore changes in the validator interface.

**Comment by djrtwo** [comment]
Thank you @raulk and @vyzo for your quick response! This ternary enum response will be immediately very valuable to eth2 :)

There are some special cases where a client might choose to _not_ forward the message but to incorporate it into the application. From the perspective of gossipsub, this just looks like an "Ignore". What is the value to libp2p/gossipsub to distinguish this Ignore-and-incorporate-to-app vs simple Ignore?

**Comment by vyzo** [comment]
We can certainly add a `DeliverOnly` value to the enum, with the semantics being "Deliver to application but don't forward". 
The difference from `Ignore` would be that the message would count as a valid delivery, and reward the peer who forwarded it.

Nonetheless, I have some reservations about whether it's the right thing to do, as we might up in a sticky situation where a node publishes a message to its immediate peers (in the mesh or via gossip/flood publishing) and all of them happen to accept it with `DeliverOnly`. 
In this case the message would be stuck in limbo: delivered to the immediate peers, but not propagated to the rest of the network.

**Comment by djrtwo** [comment]
Understand on the reservation.
I understand the distinction.. `Ignore` is fine in some of the cases I'm thinking of. Rewarding the peer isn't necessarily the obvious correct action.

With the timing issue above, the clock issue could very well be on the receiving node's side so in that case the network would likely receive the message no problem and the node with the clock issue would incorporate later.

In the case that someone's clock is way off (attacker or not) early messages not making it all the way through the network is expected behaviour, and might end with a dropped message. Especially in the case of an attacker attempting timing attacks, this is okay.

**Comment by vyzo** [comment]
> Rewarding the peer isn't necessarily the obvious correct action.

Yeah, agreed.

There is an alternative method for achieving this effect: a stateful validator that returns `Ignore` but also enqueues the message for the application to process via a side-channel.
It is not pretty, but it has very straightforward semantics and it's something one might want to experiment with.

**Comment by djrtwo** [comment]
This was addressed in v1.1 with "extended validators" https://github.com/libp2p/go-libp2p-pubsub/pull/313 and in the eth2 spec with #1796
