### ISSUE TITLE
Is the BLS test `aggregate_na_pubkeys` correct?

### ISSUE THREAD

**Issue by benjaminion** [ethereum/eth2.0-specs#1840]
There is a new BLS test [aggregate_na_pubkeys](https://media.githubusercontent.com/media/ethereum/eth2.0-spec-tests/master/tests/general/phase0/bls/aggregate/small/aggregate_na_pubkeys/data.yaml) with these contents:

```
input: []
output:
```

There seem to be two issues here:
  1. Naming. We don't have a function to aggregate public keys in the spec, only signatures. The other tests in this directory aggregate signatures. So the name should be something like `aggregate_na_signatures`, right? Or `aggregate_for_na_pubkeys` maybe.
  2. More significantly, the output. If I correctly followed the discussions below, and assuming this is about signatures rather than pubkeys, then the output ought to be `0x0000...0000` (96 bytes), right?

I'm happy to do a PR to fix this, but just want to confirm I'm not missing something.

I am aware of the conversations [here](https://github.com/ethereum/eth2.0-specs/issues/1713), [here](https://github.com/ethereum/eth2.0-specs/pull/1813), and [here](https://github.com/ethereum/eth2.0-specs/pull/1799).

**Comment by hwwhww** [comment]
@benjaminion 

> 1. Naming

Yes! Agreed with `aggregate_na_signatures`. Also need to fix the comment to signature instead of pubkey. 👍

> More significantly, the output. If I correctly followed the discussions below, and assuming this is about signatures rather than pubkeys, then the output ought to be `0x0000...0000` (96 bytes), right?

The reasons for using `None` as the output:
- IETF spec defines [`Precondition: n >= 1, otherwise return INVALID`](https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-02#section-2.8) for `Aggregate` as well, not only for pubkeys. So the issue is how to represent the `INVALID` in our test suite. It's as invalid as other invalid signature input, e.g., if the input is `[0x00..00]`, it can't be aggregated, so we throw an exception in Python.
- In PySpec, if we invoke this case in consensus code in the future, it will throw an exception to signal validation error.
- We already use `None` to represent invalid state transition cases in the state transition in the test vector, so following this pattern, we [use `None` for this invalid BLS calls as well](https://github.com/ethereum/eth2.0-specs/blob/dev/tests/formats/bls/aggregate.md#test-format-bls-signature-aggregation).

Do you think it makes sense? It does look a bit weird in YAML format though.

**Comment by mratsim** [comment]
Can't we just use "Invalid" spelled out?

**Comment by benjaminion** [comment]
I thought we'd agreed to use 0x00...00 to represent the invalid signature 🤷‍♂️. But, no matter, we can manage as long as it's clear.

**Comment by prestonvanloon** [comment]
Just to clarify, if the output is None then we are supposed to test that there was an exception or error?

**Comment by hwwhww** [comment]
@benjaminion 
> 0x00...00 to represent the invalid signature

IMO 96-byte output for the invalid cases might be confusing. That means we have to do `assert aggregate_signature != NO_SIGNATURE` after we called it.

> now throwing an exception when trying to aggregate an empty list of signatures

Thanks! I think for your implementation, it's similar to how you show it as other invalid cases you've handled already.

@mratsim 
> Can't we just use "Invalid" spelled out?

Good question! I'm not against it. /cc @protolambda 

@prestonvanloon 
> Just to clarify, if the output is None then we are supposed to test that there was an exception or error? 

Correct. :)

**Comment by benjaminion** [comment]
Seems to be sorted.
