### ISSUE TITLE
Attester Slashing Spec Test Has Bad Signatures

### ISSUE THREAD

**Issue by nisdas** [ethereum/eth2.0-specs#1841]
The attestation signatures in the slashing object are invalid for the `success_surround` test.
The following is the signature for both attestations, which is invalid: 
`0x111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111` 

https://media.githubusercontent.com/media/ethereum/eth2.0-spec-tests/master/tests/mainnet/phase0/operations/attester_slashing/pyspec_tests/success_surround/attester_slashing.yaml

**Comment by hwwhww** [comment]
@nisdas 

The [`bls_setting` of this test case was changed to `2`](https://media.githubusercontent.com/media/ethereum/eth2.0-spec-tests/master/tests/mainnet/phase0/operations/attester_slashing/pyspec_tests/success_surround/meta.yaml): known as "BLS ignored"  - if the test validity is strictly dependent on BLS being OFF in #1803.

(Since we mocked `attestation_2` by modifying the `attestation_data` and we didn't re-sign it.)

Is it okay to disable BLS verification of this case in Prysm tests?

**Comment by SatoshiNakamotogmx** [comment]
Why didn't you just tell the dam thing  to tell you who you are?  False=True(admin)guest  what do you guy have as code?   You know what I would need to see thing I feel like.   Like a kid in the middle of a conversation and don't know enough.   I'll just listen.

**Comment by nisdas** [comment]
ah k, thanks for clarifying that @hwwhww . Yeah we can disable signature verification for our tests. Closing this issue now.

**Comment by SatoshiNakamotogmx** [comment]
Email wasn't delete?

On May 22, 2020 11:37 PM, "Nishant Das" <notifications@github.com> wrote:

ah k, thanks for clarifying that @hwwhww <https://github.com/hwwhww> . Yeah
we can disable signature verification for our tests. Closing this issue now.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/eth2.0-specs/issues/1841#issuecomment-632995472>,
or unsubscribe
