### ISSUE TITLE
Security:  A malicious proposer can successfully avoid slashing (?)

### ISSUE THREAD

**Issue by kladkogex** [ethereum/eth2.0-specs#1873]
It seems that a malicious proposer that creates multiple concurrent proposals can successfully avoid slashing.

The attack goes as follows:

1.  The proposer creates zillions of conflicting proposals, causing the network to consider a great number of weak branches with no obvious winner.

2.   Note that to slash the proposer the slashing evidence needs to be included in the WINNING branch. Therefore, the strategy of the malicious party is 

  a) pick a specific branch that does not include the slashing event, and 
  b) make this branch win.

3.  Assume the malicious proposer controls a small portion of the network (say 5%).  The proposer will then make all of his guys to attest for the branch where he is not slashed.  Such a branch will inevitably exist. Assuming that other attesters vote more or less randomly, 5% will be enough to to win in the situation of havoc where all other branches are super weak.

The spec needs to at least analyze and discuss why this attack is not feasible.

**Comment by dankrad** [comment]
I don't understand how you suggest they keep the other validators from submitting the slashing message to the "winning" branch once it's the consensus?

**Comment by adiasg** [comment]
- More details on @dankrad's comment:
If a proof of two distinct blocks from the same proposer for the same slot is provided in a block, the malicious proposer is slashed in that block's chain ([here](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#proposer-slashings) is the associated spec code). Since the attacker does not control the proposers in future slots, there will be a block in the winning chain that includes a proof of the attacker's malice, which will lead to a proposer slashing.

- Regarding confusion caused by the large number of proposals for a single slot -- it is expected that the [LMD GHOST fork choice rule](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/fork-choice.md#get_head) will lead to all honest validators rapidly converging (within a few slots time) on the same chain. A simple explanation: if all honest validators see every other honest validator's attestation from the previous slot, then each of them will see the same LMD GHOST fork choice winner.

**Comment by adiasg** [comment]
@kladkogex Closing this issue. Feel free to reopen if there's more to this attack.
