### ISSUE TITLE
RFC: drop shard_and_committee_for_slots from state

### ISSUE THREAD

**Issue by arnetheduck** [ethereum/eth2.0-specs#191]
A PR to explore dropping `shard_and_committee_for_slots` from `BeaconState`. 

Pros:
* simplicity
  * clarifies functional origin and nature of data
  * less duplicated state
  * fewer mandatory state changes to keep track of
  * easier to test / verify in isolation
* smaller state - this field holds a little bit over `2 * len(validators)` entries
  * less hashing for state root
  * smaller transmit size

Cons:
* extra step for consumers of state
* "downloaded" state incomplete

practicalities:
* might need to consider an alternate approach for keeping useful `next_shuffling_seed` / `randao_seed` versions around
* #92 is related

**Comment by mkalinin** [comment]
What do you think about @djrtwo's proposal to keep `shard_and_committee_for_slots` in a separate structure with its own source and use its hash as a reference in `BeaconState`? This solution doesn't require changes in consensus and can be a part of client optimization process.

**Comment by arnetheduck** [comment]
@mkalinin I think I'm missing something - why are consensus changes needed if this field is dropped from `BeaconState`?

I'd think the other way around is more useful - that the `BeaconState` contains all seed hashes needed, such that the client can calculate the committee on the fly (basically `next_seed` and previous `next_seed` and possibly one more integer, for the round-robin index - as seen in the committee update description).

There are two reasons to do this change:

* less duplicated state in `BeaconState`
* fewer hash operations

Neither is satisfied if the hash of the committees has to end up in the `BeaconState`.

**Comment by mkalinin** [comment]
@arnetheduck _changes in consensus_ means that this proposal affects state root calculation. But since beacon chain is not yet in production this change is obviously negligible and shouldn't be taken in account.

> Neither is satisfied if the hash of the committees has to end up in the `BeaconState`.

That's not true. 
Comparing to on the fly calculation hash of committees held by `BeaconState` has only _few_ extras:
- a hash operation or even nothing, https://github.com/ethereum/eth2.0-specs/issues/231#issuecomment-444796113
- 32 bytes per each state sample; actually, this is extra `1.5GB` each 10 years with 6 seconds per slot; wondering how big this number is comparing with the others
- probably, a hash round, if size of hash function block is exceeded due to these extra bytes

There is one more thing to add here. Committees calculation has a form of `c = f(v, seed)` where `v` is a sample of validator set. And formally to perform the calculation client will have to use same sample of validator set as was used in a cycle transition that happened prior to current slot. Fortunately, according to current spec validator set is immutable between cycle transitions and sample from downloaded state could be used. This is not that bad in practice but may affect formal verification which this is out of my expertise, so, I can't judge on that.

Fast sync wise (the case when state downloading is needed). In my opinion the best option for the fast sync would be sticking with a state of last finalized slot and importing following beacon blocks approaching the head. That case calculation of committees from the state looks straightforward. What about light clients though?

In general, with regard to storing the hash, on the fly calculation looks like an over optimization to me. As for me there are no strong arguments in favor of any of these two solutions. And the question stays pretty much open.

**Comment by JustinDrake** [comment]
`shard_and_committee_for_slots` has been dropped :)
