### ISSUE TITLE
Eliminate `get_beacon_proposer_index` call in `process_randao`

### ISSUE THREAD

**Issue by terencechain** [ethereum/eth2.0-specs#1941]
I just realized one `get_beacon_proposer_index` call could be saved by passing in `block` as the argument to `process_randao`:
```python
def process_block(state: BeaconState, block: BeaconBlock) -> None:
    ...
    process_randao(state, block)
   ...

def process_randao(state: BeaconState, block: BeaconBlock) -> None:
   ...
    # Verify RANDAO reveal
    # proposer = state.validators[get_beacon_proposer_index(state)]
    proposer = block.proposer_index
```

Given we are late in the spec game, I don't have a strong desire to modify the spec to reflect such optimization and readability improvement. I just wanted to point this out because the client code could still use this change for lesser lines and/or minor speed improvement (e.g. one less look up)

**Comment by djrtwo** [comment]
I think we considered this a while back and decided that because `proposer_index` is validated in `process_block_header` that we can just safely derive it in `process_randao` and not modify the function signature.

I think we were aiming to reduce the amount of changes and new testing when `proposer_index` was added to `BeaconBlock`, and using the derivation from the block header satisfied that.

Agree that as long as `assert block.proposer_index == get_beacon_proposer_index(state)` from `process_block_header` has passed, then both ways of deriving the `proposer_index` are safe

**Comment by terencechain** [comment]
Sounds good. I will close this unless there's a strong opinion to change this in the spec
