### ISSUE TITLE
It seems that slashed validators may be selected to propose?

### ISSUE THREAD

**Issue by lucianyao** [ethereum/eth2.0-specs#1995]
At version[8e82ca5](https://github.com/ethereum/eth2.0-specs/tree/8e82ca5d1ad6d651ef3410552c4bc13c16325f63):
it seems that a slashed validator can still be selected as a proposer? I wonder if  it is by design?

**Comment by protolambda** [comment]
There's a lot to it, but I think these are the most important bits:
- If they are slashed within the same epoch, they still have their proposer slot (only if they had a proposer slot within that epoch to begin with), to not cause a sudden re-assignment of validators. Same thing for their assignment to committees. After a small piece of the system gets slashed, we don't want the complete system to shuffle everything around last-second.
- If they are slashed, they will be forced to initiate an exit. They need to go through the exit-queue like others, and will not be able to gain any rewards, while suffering inactivity penalties while queued. So no free shortcuts out of the system for bad validators.
- They are not allowed to put any blocks on chain, at any point, after being slashed. The block-header processing function aborts the state-transition if the proposer is slashed. See https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#block-header

**Comment by lucianyao** [comment]
ok, I got it, thank you. but what I am still confused are(sorry for that I probably don't comprehend the spec very well yet):
1) the slashed validators possibly are able to get proposer slots for several coming epochs instead of one epoch? Since I think the forced exit epoch can be several rounds later than current epoch, and the proposer election does exclude the slashed one? And if true, the slots are wasted.
2)regarding no.2 :the rewards, suppose validator V proposes a block at epoch E, and V is slashed at E+1, it seems that V can earn the "inclusion delay" bonus for his quick enough inclusion at E+1?

**Comment by protolambda** [comment]
> (sorry for that I probably don't comprehend the spec very well yet

No problem, ask as many questions as you like, having more external review is helpful!

> 1) the slashed validators possibly are able to get proposer slots for several coming epochs instead of one epoch?

Yes, I was having doubts about that too when reviewing things for the first answer, but think the current state is ok. The chance is very small with a large validator registry, and at worst it results in empty slots for those rare proposals.

Changing it would result in splitting the semantics of an "active validator" and one that is eligible for being selected as proposer. This increases the consensus complexity, but otherwise sounds reasonable. Right now there is at least a bias towards selecting proposers with a healthy effective balance (which only changes at epoch boundaries). See `compute_proposer_index`. So this decreases the chance of empty slots more, as slashed validators generally have a lower balance.

If we would filter on the `slashed` attribute, there may be different proposers depending on the view of the chain within the epoch. Making pre-computing (there is a little look-ahead within the epoch) of proposers more difficult.

Maybe @djrtwo has some more insight, it's an interesting edge-case.

> regarding no.2 :the rewards, suppose validator V proposes a block at epoch E, and V is slashed at E+1, it seems that V can earn the "inclusion delay" bonus for his quick enough inclusion at E+1?

If they earn an inclusion reward for proposing a block, in the epoch transition between E and E+1, that means that their block was included in the current chain, contributing to the faster inclusion of attestations. So even while they got slashed some time after rewarding them, it does not seem too bad. Maintaining a history and rolling back rewards selectively based on slashings would also increase consensus complexity a lot.

**Comment by protolambda** [comment]
Updated title to better reflect what may be wrong, since the block-header processing at least disallows the actual block.
