### ISSUE TITLE
Proposal—limit the number of active validators to 2**20

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#2065]
This issue is a proposal for discussion to limit the number of active validators to `MAX_ACTIVE_VALIDATORS = 2**20` (roughly 1m validators) instead of the current 2**22. Rationale:

1) The enshrined limit would guarantee a saner upper bound on the resource usage of a validator node (itself largely dictated by the number of active validators).
2) The enshrined limit would guarantee that the PoS inflation is no more than 1m ETH per year (making ETH-is-money folks happier).
3) It feels unlikely the limit would be reached organically. Even if validating is extremely popular and the limit is reached, validators in the activation queue can be dequeued on a first-come first-served basis. This would modify the validator assumptions (e.g. honesty or honesty assumptions) to a "rolling" variant with a large window, not too dissimilar to the status quo.

**Comment by hwwhww** [comment]
Is this proposal based on #2024?
In #2024, `MAX_ACTIVE_VALIDATORS` is an invariant of `MAX_VALIDATORS_PER_COMMITTEE * SLOTS_PER_EPOCH * INITIAL_ACTIVE_SHARDS = 2**11 * 2**5 * 2**6 = 2**22`.

**Comment by JustinDrake** [comment]
> Is this proposal based on #2024?

Nope, it's pretty independent of that.

**Comment by vbuterin** [comment]
I think we would need to do a bit more than just a constant change.

1) Actually limit the validator count (currently the limit is not even enforced). So we'd need to change

```
    for index in activation_queue[:get_validator_churn_limit(state)]:
```

To

```
    validator_count = len(get_active_validator_indices(state))
    churn_limit = get_validator_churn_limit(state)
    if validator_count > MAX_VALIDATORS_PER_COMMITTEE:
        max_additions = 0
    elif validator_count + churn_limit <= MAX_VALIDATORS_PER_COMMITTEE:
        max_additions = churn_limit
    else:
        max_additions = MAX_VALIDATORS_PER_COMMITTEE - validator_count
    for index in activation_queue[max_additions]:
```

2) To prevent awkward rapid changes, we may want to make a more graceful transition between "more validators can join" and "more validators can't join". One option would be, instead of doing the above, have `max_addition` be dynamic, and decrease more slowly to zero as the validator count reaches the max.

**Comment by JustinDrake** [comment]
closing in favour of #2137
