### ISSUE TITLE
Rollup-centric roadmap and 64 shards

### ISSUE THREAD

**Issue by ga24xoc** [ethereum/eth2.0-specs#2203]
With a rollup-centric roadmap instead of sharded execution and cross-shard transactions, wouldn´t it be easy to increase the number of shards, lets say, to the original proposed 1024?

**Comment by dankrad** [comment]
The limit on shards is mainly a bandwidth limit. We increased the per-shard bandwidth by a lot so that the total bandwidth per validator actually stays the same. But this means there is no immediate route to increase to 1024, but it should be gradually possible as internet connections speeds improve.
