### ISSUE TITLE
Beacon chain changes missing from altair/beacon-chain.md

### ISSUE THREAD

**Issue by michaelsproul** [ethereum/eth2.0-specs#2260]
There are a few changes in `specs/phase0/beacon-chain.md` that aren't reflected in the diff/summary that is `specs/phase0/altair.md`, e.g.

- `process_eth1_data_reset` is not marked `# [New in Altair]` in `process_epoch`, and its definition isn't inlined
- `process_effective_balance_updates` not marked new, not inlined
- `process_slashings_reset` not marked new, not inlined
- `process_randao_mixes_reset` not marked new, not inlined
- `process_historical_roots_update` not marked new, not inlined

(As of v1.1.0-alpha.1)

**Comment by ralexstokes** [comment]
the idea was to refactor in phase 0 so that we can more easily edit `process_epoch` moving forward as we change sub-sections of `process_epoch` or add additional epoch-level functionality.

the comments about `modified`/`new` in altair are meant to describe the state of the spec relative to the current phase 0 spec. given that we already made the refactor into subroutines in the current phase 0 spec, i'd say the items you listed do not need any of these comments (unless something is actually new that has been missed...) so we can close this issue

does that make sense or am i misunderstanding?

**Comment by ajsutton** [comment]
This had me confused for a while as well.  It may be worth a comment just to say that `process_final_updates` has been inlined in both the updated phase0 and Altair specs.  I'm not too concerned either way now that I've worked it out though.

**Comment by michaelsproul** [comment]
> the comments about modified/new in altair are meant to describe the state of the spec relative to the current phase 0 spec. given that we already made the refactor into subroutines in the current phase 0 spec

Fair enough. I initially assumed the phase0 spec was immutable between v1.0.1 & Altair, which was what lead me astray. I agree with Adrian that a comment might be nice for future readers, but now we've got our heads round it, I'm not too fussed.
