### ISSUE TITLE
Remove duplicate `CONFIG_NAME` from configs

### ISSUE THREAD

**Issue by protolambda** [ethereum/eth2.0-specs#2290]
Each configuration file has a duplicate `CONFIG_NAME` that can only result in conflicting values, and it makes it more difficult to consolidate the config files.

Discussion (@michaelsproul, @mcdee, @rolfyone): https://discord.com/channels/595666850260713488/710831784991916072/823906028600033351

> there's this weird exception right now, the `CONFIG_NAME` variable is duplicated between all configs (and might be different for unknown reasons)

> Why does CONFIG_NAME need to be in altair.yml?

> Legacy choice, I think it can be removed. My intention was always to have unique variables, simple key-value, yaml compatible, and ability to consolidate into a single namespace easily (for compatibility with env vars)

----

I think it's valuable to not have duplicate variables, and avoid dependency on them before we introduce a stable version of the first fork (Altair). In the future we may consolidate the files into a single YAML, and client implementers may do this in their internal config representation already.

**Comment by hwwhww** [comment]
Right, so the `spec.CONFIG_NAME` is for making `with_configs` work. I think it's good to keep the current separate per-fork-per-config files so that we can compare them with the specs easily.

A simple solution here, similar to ToC generation:
1. Add makefile command `make merge_config` to create merged config files: `configs/merged/<SPEC_CODE_NAME>_<CONFIG_NAME>.yaml`.
    - `phase0_mainnet.yaml`, `altair_mainnet.yaml`, `phase0_minimal.yaml`, `altair_minimal.yaml`.
    - Each merged config contains the previous forks' config + current fork config.
    - The merged file doesn't contain `CONFIG_NAME` field, but it checks if there are any conflicts except for ` CONFIG_NAME` between the atomic config files during the makefile command.
2. Add CI job to check if the merged config files are correct.
3. Output these merged config files to test vector suite output files.

**Comment by hwwhww** [comment]
closing via #2332
