### ISSUE TITLE
SSZ question: clarification on the homogeneity of list elements

### ISSUE THREAD

**Issue by cleishm** [ethereum/eth2.0-specs#232]
In the current [SSZ specification](https://github.com/ethereum/eth2.0-specs/blob/ff2551e754028260a619c1b538ac194568f1eff2/specs/simple-serialize.md#listvectors), lists are defined as "a collection of elements of the same homogeneous **type**".

By this definition, a list of byte arrays, a list of other lists, or a list of collections, are all homogeneous by *type* yet contain elements that may vary in serialized size.

The example implementations sum each elements serialized length to find the raw length, however the specification says the raw length is defined as `len(list) * sizeof(element)`, implying they all have the same serialized size. Additionally, the Tree Hash definition only uses the size of the first element in a list to calculate `items_per_chunk` (`SSZ_CHUNK_SIZE // len(lst[0])`).

The question is: should the specification define that lists contain elements of homogeneous type **and size**, or should we update the specification of raw length (e.g. to `sum(sizeof(elem) for elem in list)`) and the Tree Hash algorithm according?

**Comment by cleishm** [comment]
I also wonder if an "easier" way to resolve this would be to change the list length prefix to _only_ `len(list)` (nElements), and not the raw length of the entire list encoding. This would simplify serialization, sacrificing only the ability to skip over a complete value when decoding, which is not a common use case afaik.

Thoughts?

**Comment by jannikluhn** [comment]
I _think_ the spec is wrong and the example implementation is right. Otherwise lists of containers containing lists would not be possible, but those seem to be used in the phase 0 spec (e.g. `BeaconBlockBody.attestations`).

**Comment by cleishm** [comment]
Yeah, I agree. Though that means the Tree Hash algorithm is wrong too.

Wdyt about just using the element count?

**Comment by mkalinin** [comment]
> Wdyt about just using the element count?

When there is a need of decoding an object that have come from network it's good to know _whole size_ of encoded object. Otherwise, you have to pull list items in sequential fashion and calculate the size to mitigate overflows.

**Comment by cleishm** [comment]
> you have to pull list items in sequential fashion and calculate the size to mitigate overflows

You’re going to do that anyway though, right? Unless you’re pulling the value and _not_ decoding it, which I can’t think of a use-case for, then you’ll be iterating and decoding the length of each part. And currently you have to iterate until you find the value whose end aligns with the overall raw length (or exceeds it, which would signal an encoding error).

**Comment by mkalinin** [comment]
IMO, it's preferable to know the length of the message before processing it. It would allow reading a certain number of bytes from socket and closing it instantly. Actually, the way message is read from the socket is implementation specific, but to have alternatives here requires length prefixes in bytes.

**Comment by cleishm** [comment]
@mkalinin: in almost all cases, won't socket reads be buffered anyway? I've rarely seen a need to read only a specific number of bytes from a socket before closing it.

The advantage of only encoding the length elements actually has positive benefits for sending data - you don't have to buffer the entire list content first. One can output the number of elements to the socket, then encode and immediately output each element. If the entire raw length has to be calculated, then the entire raw list encoding has to be buffered first.

**Comment by mkalinin** [comment]
> has positive benefits for sending data

And it, also, has drawbacks for receiving them.

In case when number of elements is sent instead of length first received bytes tells almost nothing about entire message, it's just a number of elements that have an unpredictable size. Receiver starts to read these elements and calculate cumulative size. In the middle of it receiver understands that the message is too big and with high probability malformed or malicious. Then it cancels the receiving, and amount of data that have to be processed to understand whether message is sane or not is unknown before reading this message.

Another thing is that having a number of elements as a length of list does nothing with a length of container that carries some list. It should be calculated in bytes and that requires calculation of list size in bytes as well.

Another feasible way of streaming SSZ messages is to have `SSZSize(obj)` function that just calculates the size of the object in bytes. Of course, it's much less efficient than `len(list) * sizeof(element)` but that is something that could work.
