### ISSUE TITLE
`process_sync_committee` uses incorrect sync committee for first slot of new committee period

### ISSUE THREAD

**Issue by ajsutton** [ethereum/eth2.0-specs#2397]
Sorry if I've missed something here but from my understanding, the process for creating a `SyncAggregate` for a block at slot `x` is to collect the best `SyncCommitteeContribution` from slot `x - 1` and aggregate them as per `process_sync_committee_contributions` from https://github.com/ethereum/eth2.0-specs/blob/dev/specs/altair/validator.md#block-proposal.

Then during block processing, `process_sync_committee` uses `state.current_sync_committee` where `state` has already had slots processed up to and including `x`.

Given that, the aggregate indices in the `SyncAggregate` will refer to the sync committee at slot `x - 1` but if `x` is the first slot of a new sync committee period, `state.current_sync_committee` will have already been updated and now point to the new sync committee.  The wrong validator public keys will then be collected in `participant_pubkeys` and signature validation will fail.

**Comment by djrtwo** [comment]
yep, this looks correct

I'm doing some testing and a fix right now

**Comment by djrtwo** [comment]
Because we get rid of `previous_sync_committee` in state but always know `current` and `next`, the job for the `next` needs to begin 1 slot prior to the start of the period so that they can be included at the 0th slot of the period.

That is, the `current_sync_committee` votes on blocks from slots ranging `[period_start_slot - 1, period_end_slot)` and is included in blocks with slots ranging  `[period_start_slot, period_end_slot]`
