### ISSUE TITLE
Unused parameter in pyspec test code

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/eth2.0-specs#2425]
https://github.com/ethereum/eth2.0-specs/blob/dev/tests/core/pyspec/eth2spec/test/helpers/attestations.py#L53

The `on_time` parameter is not used. Unsure if it should have any particular meaning, but it does seem to be used like it should, for example
```python
get_valid_on_time_attestation

get_valid_late_attestation
```
 
in the same file.

**Comment by djrtwo** [comment]
This was a relic of a pretty complex sharding design that had a notion of on-time and late attestations that validators would rebroadcast if they didn't get an attestation included in the next slot. 

This is no longer the case in the simplified sharded data design (primarily because there is no longer a notion of "chainedness" in shards). And should probably be cleaned up from the testing helpers

**Comment by ralexstokes** [comment]
yeah i was wondering if it was connected to that notion of "timeliness" -- i can make a note to clean up at some point
