### ISSUE TITLE
Incorrect state root in transition test block

### ISSUE THREAD

**Issue by ajsutton** [ethereum/eth2.0-specs#2439]
In `minimal/altair/transition/core/pyspec_tests/transition_with_finality/blocks_0.ssz_snappy` the state root is `0x0000000000000000000000000000000000000000000000000000000000000000` so Teku rejects the block as invalid. 

`blocks_1.ssz_snappy` appears to have a non-zero state root so not sure what happened to this first block.  Same problem occurs in a few other transition tests as well for both mainnet and minimal config:

* `transition_with_no_attestations_until_after_fork`
* `transition_with_random_half_participation`
* `transition_with_random_three_quarters_participation`

**Comment by ajsutton** [comment]
Interestingly a couple of the tests seem to have the first block right but then a zero state root at later blocks.  Like transition_with_no_attestations_until_after_fork which fails to process blocks_16.ssz_snappy (in minimal - blocks_64.ssz_snappy in mainnet).

**Comment by terencechain** [comment]
Thanks for this! I also can confirm this abnormality while testing Prysm

**Comment by ralexstokes** [comment]
ah, i have misused some of the helper code in the pyspec testsuites so the state root was not being set correctly -- thanks for raising this, i'll have a fix up soon

**Comment by ralexstokes** [comment]
the fix for this should be in #2443. i was able to verify all the blocks for the minimal setting were well-formed, had signatures and state roots. i was not able to verify the mainnet setting as i'm lacking up-to-date code for the latest spec version but they should follow the minimal outcome on this issue. please let me know if you run into any other errors!
