### ISSUE TITLE
Can't publish SyncCommitteeSignature to multiple subnets

### ISSUE THREAD

**Issue by ajsutton** [ethereum/eth2.0-specs#2471]
We’re hitting some interesting problems with publishing sync committee signatures when they have to be sent to multiple gossip topics (the validator is included in the sync committee multiple times, in different subnets).  This is extremely unlikely to happen on MainNet or the public testnets but very common on small scale test networks used during development or in automated tests.

Firstly, jvm-libp2p is tracking seen messages globally, not per topic so just ignores the request to publish to the additional topics because it’s already been sent once. Apparently the rust implementation applies the same restriction.  This makes it impossible to implement the validator spec correctly since the same signature can't be published to multiple subnets.

Secondly, the eth2 p2p-networking spec, explicitly has:
```
•	[IGNORE] There has been no other valid sync committee signature for the declared slot for the validator referenced by sync_committee_message.validator_index.
```
I believe this is meant to be per-subnet but we should make that clearer.

**Comment by ajsutton** [comment]
One option would be to change the `SyncCommitteeMessage` to include the subnet ID:
```python
class SyncCommitteeMessage(Container):
    # Slot to which this contribution pertains
    slot: Slot
    # Subcommittee index 
    subcommittee_index: uint64 # or maybe smaller
    # Block root for this signature
    beacon_block_root: Root
    # Index of the validator that produced this signature
    validator_index: ValidatorIndex
    # Signature by the validator over the block root of `slot`
    signature: BLSSignature
```

Since the BLS signature is only over the `beacon_block_root` a single BLS signing operation can be performed and only the `subcommittee_index` needs to be changed when publishing to different subnets.

**Comment by michaelsproul** [comment]
We had the same validation issue in Lighthouse, and will fix it in advance of any changes to the types themselves.

An alternative to the wrapper type would be to keep both representations, using the one with `subcommittee_index` in consensus (and everywhere except the API). The API could then define its own type equivalent to the current `SyncCommitteeMessage` called something like `FreeSyncCommitteeMessage`.

```python
class FreeSyncCommitteeMessage(Container):
    # Slot to which this contribution pertains
    slot: Slot
    # Block root for this signature
    beacon_block_root: Root
    # Index of the validator that produced this signature
    validator_index: ValidatorIndex
    # Signature by the validator over the block root of `slot`
    signature: BLSSignature
```

I'm also not sure of the name :sweat_smile:

**Comment by ralexstokes** [comment]
> Do we even need the subcommittees? It might be too late to make this kind of change, but it seems like a lot of nuance for reducing the messages we might get by a couple of hundred... I assume it's to reduce the load on light clients...

aggregation is used here to bound the additional load on the entire validator set required to support the sync committees in the first place -- we currently have no lookahead on the proposer duty which means validators should always be listening to the global channel `sync_committee_contribution_and_proof` in order to be able to collect the sync committee proposer rewards (the underlying assumption is that proposers will not be able to find peers and gather the right gossip in time if they wait until the epoch they discover they should propose in). 

without aggregation, all validators would need to listen to traffic from an additional `SYNC_COMMITTEE_SIZE` validators each slot. with aggregation, that load is reduced by a factor of `SYNC_COMMITTEE_SUBNET_COUNT` and with the current parameters works out to something on the order of an additional attestation committee (~128 validators).

i don't see an immediate reason light clients would want to follow the gossip at this stage of the process; more likely they will want updates on a separate network once signatures actually make it on-chain, get finalized, etc.
