### ISSUE TITLE
Yet another possible alternative to current header/body separation

### ISSUE THREAD

**Issue by vbuterin** [ethereum/eth2.0-specs#264]
```
BeaconBlock: {
    "parent_hash": 'hash32',
    "body": BeaconBlockBody
}
```

```
BeaconBlockBody: {
    'ancestor_hashes': ['hash32'],
    'state_root': 'hash32',
    'randao_reveal': 'hash32',
    'candidate_pow_receipt_root': 'hash32',
    'signature': ['uint384'],
    'attestations': [Attestation],
    'proposer_slashings': [ProposerSlashing],
    'casper_slashings': [CasperSlashing],
    'deposits': [Deposit],
    'exits': [Exit],
}
```

Rationale: now you can download an entire mini-chain with just 32 bytes per block.

I'm not sure whether or not I agree with doing this BTW, just wanted to raise it for discussion.

**Comment by mkalinin** [comment]
IMO chain of headers (or however it's called) would be useful if it would be feasible to check whether it's valid or not. Otherwise, it becomes unreliable. One of the applications of this _mini-chain_ could be in fork handling which seems not so useful without reliability. 

I am starting to think that chain of headers is not a valuable thing for the beacon chain. For example, it could not be verified without knowing all `shard_committees_at_slots` and `validator_registry` samples that were used to build this chain. Which looks pretty inefficient.

**Comment by mkalinin** [comment]
> Considering most syncs will be from a known finalized slot

This assumption might require a separate discussion. The main question is how to prove that given finalized slot is a product of a sequence of valid state transitions originated from a certain `initial_state`?

**Comment by nisdas** [comment]
@mkalinin  As far as I can see the only way we could verify would be to download all the blocks from genesis till the last finalized slot in order to determine that the state transitions were all valid.

**Comment by zah** [comment]
I've described one possible efficient syncing scheme here:
https://notes.ethereum.org/s/BJPBa42TQ#Beacon-chain-sync

The general idea is that you'll be syncing primarily the changes in the validator set by obtaining a very sparse set of blocks where a super-majority of the validators known to you have signed a new `validator_registry_delta_chain_tip` hash. Once you know the latest validators, it's enough to obtain only the latest block, because through the slashing rules, the timestamp of the block (its slot number) and the signatures of the validators are enough to authenticate it.

We hope to run an experiment with a proof-of-concept implementation of this scheme in the December release of Nimbus.

**Comment by mkalinin** [comment]
Thanks @zah for sharing this scheme! Indeed, it looks pretty efficient, at least for light clients. 

For those who don't want to stick with weak subjectivity, this scheme could be featured with additional accumulator for `next_seed`, e.g. `seed_update_root`, which is similar thing as `validator_registry_delta_chain_tip`. Then by downloading a chain of headers and requesting tips on validator set changes and seed updates (upon they are detected) it would be possible to get a consensus proof of validity of state that corresponds to the finalized slot.

This approach would require to store historical data like headers and tips, though. Not that big as a history of block bodies but still something that will be constantly growing.

**Comment by djrtwo** [comment]
@vbuterin Do you still want to make a case for this format?

**Comment by JustinDrake** [comment]
I think we're sticking with what we have now :)
