### ISSUE TITLE
discussion on latest_hash and state_transition function signature

### ISSUE THREAD

**Issue by arnetheduck** [ethereum/eth2.0-specs#284]
https://github.com/ethereum/eth2.0-specs/blob/2facc754ccc9c57191e51e596db9705133520abe/specs/core/0_beacon-chain.md#per-slot-processing

`latest_hash` is added to `state` before verifying that `latest_block` is sane (has the right slot number etc) - is this the intention?

**Comment by djrtwo** [comment]
yes, there is a block hash added to the state per slot. This allows  for a simple 1-to-1 mapping of state to a given hash that can be voted on by attesters. Practically it means -- if I don't see a new block come in for slot S, I vote on whatever the previous block I did see come in. This also ensures that we have a block hash to vote on at every epoch boundary which are ultimately the blocks that are being targeted by the Casper mechanism.

One thing that I'm not too happy with is that the state transition function signature is something like `slot_state_transition(prev_state, latest_block, new_block) -> new_state` rather than `slot_state_transitioni(prev_state, new_block) -> new_state` (where `new_block` can be empty in each).
Ideally I'd like for the state transition function just to be a function of `state` and `new_block`, but it seems tough to avoid in this new per-slot transition.

**Comment by arnetheduck** [comment]
Right - looks like I misread the spec, assuming that `latest_block` is the same as `Let block be that associated incoming block.` just below - all clear then! That signature helped clear it up.

Sounds reasonable that it would be nice to avoid, though I'm not yet that far into the spec. What are problem areas?

**Comment by djrtwo** [comment]
When we had per-block transition, we would just use the parent_hash from the incoming block and back-fill all the skipped slots. Now that we are doing per-slot transition, we need to know the previously processed block without necessarily having a new block come in.

First impression is to just save the current block being processed into the state rather than always inputing the _previous_. Because `block.state_root` is tree_hash of the post-state root, you can't just naively put the current block into the state. you end up with a circular reference.

Calling it a night, but curious to hear your thoughts

**Comment by mkalinin** [comment]
What if append `latest_block_hashes` with either `latest_hash` or `block_hash` (depending on whether block from proposer exists) at the end of state transition?

**Comment by djrtwo** [comment]
This messes with the `block.state_root` representing the actual state.

If you do the following, it's essentially the same thing as independently carrying the latest_block because it doesn't get embedded in the blocks state_root and is a local consideration.
* process state transition
* check/set state root
* add block to state

**Comment by mkalinin** [comment]
> Because block.state_root is tree_hash of the post-state root, you can't just naively put the current block into the state. you end up with a circular reference.

Now I get it. And looks like current spec version describes the only possible way of tracking `latest_block_roots`.

The other question is whether `latest_block_roots` should be a part of the state or not. On one hand it's pretty helpful to have them in there, but on the other they are redundant in terms of consensus. This question is similar to https://github.com/ethereum/eth2.0-specs/issues/191 and IMHO we should get back to them later when wire protocol is designed and sync algorithm is clarified. It would give us more insight on what should be in the state and what's not.

**Comment by mkalinin** [comment]
It definitely a thing that is required by processing. 
> The other question is whether `latest_block_roots` should be a part of the state or not.

By this statement I just meant that it could be tracked by client implementation and not being a part of the sate.

**Comment by JustinDrake** [comment]
> not being a part of the sate.

If we want `state_transition(prev_state, new_block) -> new_state` (which I think is a sane property to have) then `latest_block_roots` should be part of the state.

**Comment by djrtwo** [comment]
I'm actually re-thinking it, and the function signature is actually okay.

State transition looks like the following (assuming that the `prev_state` is the resulting state of processing the block defined by `new_block.parent_root`):

```python
def state_transition(prev_state, new_block) -> new_state:
    state = deepcopy(prev_state)
    latest_root = new_block.parent_root

    # transition through skipped slots
    while(state.slot <= new_block.slot - 1):
        state = per_slot_state_transition(state, latest_root, block=None)

    # transition through slot of the new block
    state = per_slot_state_transition(state, latest_root, new_block)

    return state
```

the slots processed without an associated block are just an internal portion of this ultimately per-block state transition.

**Comment by arnetheduck** [comment]
just a note, because it's not visible: in the above state transition function, it's good to remember that epoch processing is done even when there's no block - at least that's how I read the spec

**Comment by djrtwo** [comment]
You can opportunistically transition locally, but until you get a new block in, you don't know what slot it's parent will be.

Say your last block is block `B` at slot 50. Slots are ticking away... 51, 52, 53.... 64 arrives and no new block. I can opportunistically transition through all of these skipped blocks. Now I'm locally at slot 64 and done an epoch transition. If a new block `C` comes in with parent `B` at slot 63, I now would have to roll back to slot 62 and transition slot 63 with block `C`.

Another option is to sit there with block `B` and do nothing with my local state until I get a new child block, catching up slots in the state transition as needed.

There are some trade-offs here depending on how/when new shufflings/duties appear. Will think on it and write some more notes tomorrow.

**Comment by arnetheduck** [comment]
> I now would have to roll back

well, that can happen anyway, when fork choice says so?

**Comment by JustinDrake** [comment]
It seems that the issues raised have been addressed/answered. Feel free to reopen @arnetheduck :)
