### ISSUE TITLE
Keep latest 2^n RANDAO mixes in the state

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#295]
Several reasons:

* Allows to change the RNG lookahead (currently at least 1 epoch) without messing with the `BeaconState` format.
* Allows to expose randomness as an opcode in the EVM 2.0 (similar to the `BLOCKHASH` opcode).
* Useful for the VDF logic. (Note: the plan is to include VDF placeholders in the `BeaconState`.)

**Comment by djrtwo** [comment]
Also ensures that we have the seed of the current shuffling _in state_. Right now, we discard the current shuffling seed immediately after performing the shuffling. Not very friendly for reconstructing the shuffling outside the specific state transition.

**Comment by JustinDrake** [comment]
> Not very friendly for reconstructing the shuffling outside the specific state transition.

To reconstruct the shuffling you also need the validator registry, and that will have moved on right?

**Comment by djrtwo** [comment]
Not if you are two blocks into an epoch. The source of the current shuffling has been discarded. If say, I am a validator or user application querying a node through an RPC interface, it becomes opaque to me if the current shuffling has changed say due to a fork because the seed source of the shuffling is query-able (unless it is just stored locally).

Regardless, your solution keeps it around which I support

**Comment by vbuterin** [comment]
Solved with https://github.com/ethereum/eth2.0-specs/pull/327
