### ISSUE TITLE
get_block_root handling of exception case

### ISSUE THREAD

**Issue by dangerousfood** [ethereum/eth2.0-specs#368]
In the [get_block_root](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#get_block_root) method:

```
get_block_root
def get_block_root(state: BeaconState,
                   slot: int) -> Hash32:
    """
    Returns the block root at a recent ``slot``.
    """
    assert state.slot <= slot + LATEST_BLOCK_ROOTS_LENGTH
    assert slot < state.slot
    return state.latest_block_roots[slot % LATEST_BLOCK_ROOTS_LENGTH]
```

If the two assertion fails is this an exception case?

**Comment by djrtwo** [comment]
`assert`s need to be handled as you see fit in your codebase.
In most of the helpers, the asserts are putting the bounds on what data can be retrieved from state at the current state.

If processing a block caused an assert to fail, then the block would be seen as invalid because the state transition can not be processed due to some exceptional data being present. In this case, I might throw something like a `ValidationError` or `ValueError` that would be caught by an outer block processor that then discards the block as invalid.
