### ISSUE TITLE
Conditional in Casper / Proposer Processing Never Triggered

### ISSUE THREAD

**Issue by rauljordan** [ethereum/eth2.0-specs#415]
Hi all,

Looking at the following lines in proposer and casper slashings in block operations:

```
Verify that validator.penalized_slot > state.slot
```

and
```
For each validator index i in intersection run penalize_validator(state, i) if state.validator_registry[i].penalized_slot > state.slot
```

`validator.penalized_slot` is only updated in the `penalize_validator` function, but this function is only used in the spec if the previous conditional passes. The code above will never run as `penalized_slot` will always be the default value of `FAR_FUTURE_SLOT`. Am I missing something?

**Comment by djrtwo** [comment]
The following line ensures that the validator has not yet been penalized. If the validator _has_ been penalized by another operation, then the `penalized_slot` will be `<= state.slot` because it either happened at this slot or in the past. If the validator _has not_ been penalized already, then their `penalized_slot` will be `== FAR_FUTURE_SLOT` and certainly greater than `state.slot`
```
Verify that validator.penalized_slot > state.slot
```

The following line is a similar catch to prevent double penalization in attestations. It runs penalization for the set of slashable validators that have not yet been penalized. Some  validators might have been slashed via some other message so this ensures that we don't overwrite a previously set `penalized_slot`
```
For each validator index i in intersection run penalize_validator(state, i) if state.validator_registry[i].penalized_slot > state.slot
```

**Comment by djrtwo** [comment]
I'm pretty sure these conditions are correct as is. Does that make sense? Am I missing something?

**Comment by rauljordan** [comment]
Hey Danny this makes sense - it serves as protection against other operations or functions mutating that field and causing an inconsistent condition. To add to my confusion, we had not yet updated our beacon config so the default penalized slot in Prysm was 0 instead of FAR_FUTURE_SLOT, which I think was the root of my problem.

This issue can be closed, thank you!
