### ISSUE TITLE
Refactor signature handling

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#540]
Right now the signature logic across SSZ object is ad-hoc. The following are dealt differently:

* Beacon blocks: custom signed header
* Attestations: external signature
* Exits: overwrite `signature` field with 0x0
* RANDAO reveals: sign raw data

Here's one way to unify the signature logic (discussed with Danny and Vitalik):

* Remove signatures from the existing SSZ objects
* For every SSZ object `o` have a corresponding "signature header" `h` and canonical signature `h.signature`.
* The signature header `h` is defined below, where `h.root = tree_hash_root(o)` and `h.signature = bls_sign(h)` of where `h.signature` is first set to `EMPTY_SIGNATURE `.

```
{
    epoch: Epoch,
    shard: Shard,
    root: Bytes32,
    signature: Signature,
}
```

**Comment by vbuterin** [comment]
Adding an empty signature field to _every_ SSZ object seems like a bad idea; it would just add a lot of hashing overhead. The cleanest would just be for every type `T` have a type `SignedT = {data: T, signature: Signature}`.

However there is another issue which is that for attestations, we need to have the attestation and custody bitfields not be signed over, because the signers don't know who each other are, so the signature mechanism is not going to fit it well no matter how it is done.

Another possibility is to establish a rule that the signature is the signature of all fields that come before it. This way we can just use order of appearance in the object to denote order of signing and what does and does not need to be signed.

**Comment by JustinDrake** [comment]
Closing in favour of #649.
