### ISSUE TITLE
GRANDPA consensus

### ISSUE THREAD

**Issue by jamesray1** [ethereum/eth2.0-specs#557]
Please have a look at https://github.com/w3f/consensus/blob/master/pdf/grandpa.pdf, and give your feedback vs. FFG and CBC. Note that this is pre-emptive opening this as I haven't finished reading the paper yet myself. Section 1.4 compares with Casper: https://raw.githubusercontent.com/w3f/consensus/master/pdf/grandpa.pdf#subsubsection.1.4.1. Use a Chromium browser to view this link, it doesn't work for me in Firefox, even with Preview PDF in Firefox set (by default) and the No PDF Download extension.

**Comment by jamesray1** [comment]
Care to respond?

**Comment by djrtwo** [comment]
Parity is currently building a 2.0 client in substrate. Although the promise of using substrate is high, they have had to make a few modifications to the underlying framework to accommodate for the 2.0 design (for example, being able to evaluate fork choice at slot boundaries rather than just when receiving a block).

I have not done a deep dive on GRANDPA but FFG and GRANDPA satisfy many of the same design goals -- finality gadget on top of a chain, safety under asynchrony, and plausible liveness. FFG is well studied and understood by the protocol researchers designing 2.0 and is already integrated into the spec. I don't expect the consensus algorithm at this point to change without a powerful argument.

It is far more likely that we switch the consensus algorithm to a different family with more desirable properties in the long term rather than switching from FFG to another finality gadget. For example, CBC for the beacon chain is under R&D, and looks promising in resolving issues that arise between the finality gadget and the fork choice.

**Comment by JustinDrake** [comment]
> I don't expect the consensus algorithm at this point to change

I'll second that. No actionable spec changes in this direction in the short term. Nudging the discussion towards ethresear.ch :)
