### ISSUE TITLE
Deposit contract needs to check length of deposit data

### ISSUE THREAD

**Issue by vbuterin** [ethereum/eth2.0-specs#710]
The deposit contract needs to actually verify that the deposit data is **exactly** 192 bytes long (that's `len(ssz_serialize(deposit_data))`), 192 = 8 (amount) + 8 (timestamp) + 48 (pubkey) + 32 (withdrawal credentials) + 96 (proof of possession).

The reason is that if a deposit data is submitted that is NOT 192 bytes, it is impossible to create a DepositData that serializes to the hash put into the Merkle branch, which could be used to prevent progress of deposit processing.

**Comment by JustinDrake** [comment]
Note that `ssz_serialize` currently includes a 4-byte length prefix.

@protolambda notes that any composite object (container, list, tuple) can contain a variable-length sub-object by embedding a list. We can't really put length prefixes for all everywhere because serialising something as trivial as chunk list `byte[32][]` would have an overhead of 4 bytes per chunk.

To solve the `ssz_serialize(deposit_data)` length prefix issue, and the overhead issue from superfluous length prefixes, my suggestion is to only add a length prefix for variable-size containers/lists/tuples, i.e. containers/lists/tuples that embed a list. Thoughts?

**Comment by vbuterin** [comment]
From an implementation point of view, that would require keeping track of whether or not each type that's a member of some type contains any variable-length elements. I suppose that's reasonable and not very difficult. And definitely more elegant than modifying the deposit contract to add the `\xc0\x00\x00\x00` before every deposit to make it technically SSZ compliant.

**Comment by djrtwo** [comment]
We now put a max bound on the size of the `deposit_data` using vyper typing `def deposit(deposit_data: bytes[184])` but I'm pretty sure a user can still submit _less than_ the prescribed type length. 

We still need to add an assertion that the `deposit_data` length is _exactly_ 184 bytes.

cc: @NIC619

**Comment by JustinDrake** [comment]
PR #924 suggests using Vyper typing `def deposit(pubkey: bytes[48], withdrawal_credentials: bytes[32], amount: bytes[8], signature: bytes[96])` instead.

**Comment by djrtwo** [comment]
Fair, will still need to assert lengths or pad out (assert lengths is safer for users)

**Comment by hwwhww** [comment]
link https://github.com/ethereum/deposit_contract/pull/37

**Comment by hwwhww** [comment]
close via ethereum/deposit_contract#37
