### ISSUE TITLE
Remove DepositData

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#760]
Currently `DepositData` is:

```python
{
    # Amount in Gwei
    'amount': 'uint64',
    # Timestamp from deposit contract
    'timestamp': 'uint64',
    # Deposit input
    'deposit_input': DepositInput,
}
```

We already discussed removing `timestamp`. Further, we can put `amount` inside `DepositInput` because (unlike `timestamp`) it is known ahead of time and can be signed over by the `proof_of_possession`.

This would allow us to reduce to two objects for deposits: `Deposit` and `DepositInput`. (We could then rename `DepositInput` to `DepositData` for consistency.)

**Comment by vbuterin** [comment]
Nice! Hooray for simplification.

> We already discussed removing timestamp.

To clarify to those who weren't in the call, the original justification for timestamp was to put a time limit on deposit inclusion so that deposit receipts cannot be "double-spent". However, this is no longer necessary because we are forcing eth1 deposits to be processed in order.
