### ISSUE TITLE
SSZ length for Hash256, Signatures, Public Keys and Booleanbitfields?

### ISSUE THREAD

**Issue by kirk-baird** [ethereum/eth2.0-specs#837]
Hi all,

I was wonder for which of the following types would require a length and which will not.
- `Address = 'bytes20'`
- `Hash256 = 'bytes32'`
- `AggregateSignature = 'bytes96'`
- `Signature = 'bytes96'`
- `PublicKey = 'bytes48'`
- `BitField = 'bytes'`

I was wonder for the types with a strict length (Hash, Signature, PublicKey) whether SSZ should prepend the first 4 bytes with the length?

Also am I correct in assuming that BooleanBitfield the length would always be required as the number of bytes would vary?

**Comment by CarlBeek** [comment]
So from the SSZ spec, `"bytesN"` is an alias for `["byte", N]` (where`"byte"` is an alias for `"unit8"`) which is a fixed length object (either called a **"tuple"** or a **"vector"** depending on your version of the spec). The SSZ spec further specifies that fixed size objects do not have the length to be included in the serialisation (as that would be superfluous).

The BitField is a `"bytes"` which is an alias for `["byte"]` which is a **"list"** and therefore not fixed in length and therefore the length is prepended. This is for precisely the reason you point out in your issue.

**Comment by kirk-baird** [comment]
Cool makes sense to me.
Thanks for the explanation :smile:
