### ISSUE TITLE
get_base_reward in GENESIS_EPOCH is 0, so all rewards are zero

### ISSUE THREAD

**Issue by dankrad** [ethereum/eth2.0-specs#941]
`get_base_reward` uses `get_previous_total_balance`, but this returns 0 during the genesis epoch. So all rewards are zero in the `GENESIS_EPOCH`.

Why are we using `get_previous_total_balance` here and not `get_total_balance`? The latter seems to make more sense to me.

If there is a good reason why we want to use `get_previous_total_balance`, we can set         `validator.activation_epoch = GENESIS_EPOCH - 1` for validators activated at genesis?

**Comment by djrtwo** [comment]
The key here is that rewards are given for activity during the previous epoch. Because we want to give all attestations an entire epoch to be included on chain, we have to wait until the end of the following epoch to reward attestations from the previous.

Some of this changes here -- https://github.com/ethereum/eth2.0-specs/pull/896

Rewards are given for activity in the previous epoch so we just skip rewards calculations during the genesis epoch. It is using previous_total_balance to reward based upon your balance during the epoch in which you produced the `attestation`.

**Comment by dankrad** [comment]
So ignoring #896, not sure if it has been fixed there, I think this is actually a bug.

At the end of GENESIS_EPOCH, we do the per-epoch processing for the GENESIS_EPOCH. So at that time, 64 blocks and the corresponding attestations will have been processed, and should be rewarded. However, get_base_reward will be called, and will always return 0 (you can test this by putting an assert False in the return 0 case, all test cases with epoch transitions will fail). This is because at GENESIS_EPOCH-1, the total balance was actually 0.

**Comment by JustinDrake** [comment]
> At the end of GENESIS_EPOCH, we do the per-epoch processing for the GENESIS_EPOCH.

The processing of `GENESIS_EPOCH` attestation rewards happens at the end `GENESIS_EPOCH + 1` (as opposed to `GENESIS_EPOCH`).

**Comment by dankrad** [comment]
> > At the end of GENESIS_EPOCH, we do the per-epoch processing for the GENESIS_EPOCH.
> 
> The processing of `GENESIS_EPOCH` attestation rewards happens at the end `GENESIS_EPOCH + 1` (as opposed to `GENESIS_EPOCH`).

I see, but then why are we using the current balance for the validator, but the previous epoch balance for the total balance? I don't understand the logic behind this.

Also, I would suggest we add more context for logic like this. so that code like this can be understood easily without needing to refer to previous discussion (also goes with #942).

**Comment by JustinDrake** [comment]
> why are we using the current balance for the validator, but the previous epoch balance for the total balance?

Good question! The reason is that we would need two balances per validator. See the note in the spec:

> "Total balances computed for the previous epoch might be marginally different than the actual total balances during the previous epoch transition. Due to the tight bound on validator churn each epoch and small per-epoch rewards/penalties, the potential balance difference is very low and only marginally affects consensus safety."

> I would suggest we add more context for logic like this. so that code like this can be understood easily without needing to refer to previous discussion

Yes, there's still a lot of work on presentation and education. One of the things I intend to do when the spec is finalized is write the Ethereum 2.0 "transparent paper" which provides context for various design decisions, in addition to being written with readability as the top priority.

**Comment by JustinDrake** [comment]
> the real balance is just always "one epoch behind"

Interesting

> except for top-ups, but they are not handled correctly by the current logic either

How are top-ups currently incorrectly handled?

> With the current approach, it is very difficult to find bugs by methods other than writing tests

Please submit PRs fixing the current approach :)

**Comment by dankrad** [comment]
> How are top-ups currently incorrectly handled?

By this I mean that a validator can attest in epoch N, deposit (if we allow that, which it currently looks like) in epoch N+1, and get their rewards as if they had had the new balance already in epoch N.

> Please submit PRs fixing the current approach :)

I can do that if I get buy in on #942 :)

**Comment by JustinDrake** [comment]
I think this is addressed by #949. Please close if so :)
