### ISSUE TITLE
Avoid invalid BeaconState in tests

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#954]
I have started writing invariants and running them against the sanity tests. The invariant

```python
            if v.slashed or balance < EJECTION_BALANCE:
                assert v.exit_epoch != FAR_FUTURE_EPOCH
```

fails on `test_transfer()` which artificially creates an invalid state:

```python
    # un-activate so validator can transfer
    pre_state.validator_registry[sender_index].activation_epoch = spec.FAR_FUTURE_EPOCH
```

Should we stick with valid pre-states in the tests (i.e. avoid hacks such as the above)?

cc @djrtwo

**Comment by djrtwo** [comment]
agh. I see the value. It just makes writing tests so much easier (and less computationally complex!).
Can do a pass on cleaning this up with increased helpers to modify state in safe ways.

**Comment by protolambda** [comment]
Can we close this? I don't think it's viable to put all tests into such invariant passing state efficiently (and it increases complexity/maintenance). I'd rather have more coverage, and have invariants running on fuzzing + testnets.

**Comment by JustinDrake** [comment]
> I don't think it's viable to put all tests into such invariant passing state efficiently 

Really? Back then it was only a single test not passing my invariants.

**Comment by protolambda** [comment]
I mean, we can try, but since then we introduced quite a few tests. I think using invariants on fuzzing is much more valuable to find actual bugs.

Fuzzing makes any arbitrary block, but works on a valid pre-state: everything that goes and doesn't pass invariants is a bug.

Whereas tests make a specific artificial pre-state and minimal change, to test the unit of logic triggered by that change; we'd pass through logic that's not part of the unit we're testing if we build a non-artificial pre-state (that may be very far in the future, not something from genesis). Keeping focus on one part of the spec is good for testing imho, as it narrows down the cause of failure a lot.

**Comment by djrtwo** [comment]
This is no viable at this point. States are manually modified to produce particular scenarios throughout testing.

adding invariants to the fuzzing and/or FV infrastructure could be valuable
